In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [2]:
data= pd.read_csv("data/fra_cleaned.csv", sep=";")

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24063 entries, 0 to 24062
Data columns (total 18 columns):
 #   Column                                                                       Non-Null Count  Dtype
---  ------                                                                       --------------  -----
 0   url                                                                          24063 non-null  object
 1   Perfume                                                                      24063 non-null  object
 2   Brand                                                                        24063 non-null  object
 3   Country                                                                      24063 non-null  object
 4   Gender                                                                       24063 non-null  object
 5   Rating Value                                                                 24063 non-null  object
 6   Rating Count                                                                 24063 non-null  int64
 7   Year                                                                         22026 non-null  float64
 8   Top                                                                          24063 non-null  object
 9   Middle                                                                       24063 non-null  object
 10  Base                                                                         24063 non-null  object
 11  Perfumer1                                                                    24063 non-null  object
 12  Perfumer2                                                                    1336 non-null   object
 13  mainaccord1                                                                  24063 non-null  object
 14  mainaccord2                                                                  24050 non-null  object
 15  mainaccord3                                                                  23949 non-null  object
 16  mainaccord4                                                                  23675 non-null  object
 17  mainaccord5,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,  24063 non-null  object
dtypes: float64(1), int64(1), object(16)
memory usage: 3.3+ MB

In [4]:
data.describe()

       Rating Count          Year
count  24063.000000  22026.000000
mean     501.396542   2012.455961
std     1429.484690     13.526737
min       26.000000   1781.000000
25%       56.000000   2010.000000
50%      127.000000   2015.000000
75%      360.000000   2019.000000
max    29858.000000   2024.000000

In [ ]:
data.sample()

,url,Perfume,Brand,Country,Gender,Rating Value,Rating Count,Year,Top,Middle,Base,Perfumer1,Perfumer2,mainaccord1,mainaccord2,mainaccord3,mainaccord4,"mainaccord5,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"
21297,https://www.fragrantica.com/perfume/paris-elys...,la-petite-fleur-secrete,paris-elysees,India,women,"4,28",43,2017.0,"tangerine, water jasmine, ginger flower","salt, vanilla","ambergris, cashmeran, sandalowood",unknown,NaN,vanilla,salty,powdery,woody,"citrus,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..."

In [6]:
data.shape

(24063, 18)

In [7]:
data.dtypes

url                                                                             object
Perfume                                                                         object
Brand                                                                           object
Country                                                                         object
Gender                                                                          object
Rating Value                                                                    object
Rating Count                                                                     int64
Year                                                                           float64
Top                                                                             object
Middle                                                                          object
Base                                                                            object
Perfumer1                                                                       object
Perfumer2                                                                       object
mainaccord1                                                                     object
mainaccord2                                                                     object
mainaccord3                                                                     object
mainaccord4                                                                     object
mainaccord5,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,     object
dtype: object

In [8]:
data.isnull().sum()

url                                                                                0
Perfume                                                                            0
Brand                                                                              0
Country                                                                            0
Gender                                                                             0
Rating Value                                                                       0
Rating Count                                                                       0
Year                                                                            2037
Top                                                                                0
Middle                                                                             0
Base                                                                               0
Perfumer1                                                                          0
Perfumer2                                                                      22727
mainaccord1                                                                        0
mainaccord2                                                                       13
mainaccord3                                                                      114
mainaccord4                                                                      388
mainaccord5,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,        0
dtype: int64

In [9]:
data.nunique()

url                                                                            24063
Perfume                                                                        22840
Brand                                                                           1060
Country                                                                           54
Gender                                                                             3
Rating Value                                                                     221
Rating Count                                                                    2721
Year                                                                             145
Top                                                                            18771
Middle                                                                         19690
Base                                                                           16393
Perfumer1                                                                        869
Perfumer2                                                                        259
mainaccord1                                                                       66
mainaccord2                                                                       71
mainaccord3                                                                       72
mainaccord4                                                                       69
mainaccord5,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,     1229
dtype: int64

Ratig Values datatype is object and instead of decimals, commas have been used. we need to replace the comma with decimal and the conert it from strig to float

In [11]:
data["Rating Value"]= data["Rating Value"].str.replace(",", ".").astype(float)

In [16]:
data["Rating Value"].dtype

dtype('float64')

In [17]:
data["Rating Value"].head()

0    1.42
1    1.86
2    1.91
3    1.92
4    1.93
Name: Rating Value, dtype: float64